# Generated by Django 3.2 on 2021-12-23 05:56

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('workouts_description', models.TextField(blank=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('workouts_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('workouts_created_on', models.DateTimeField(auto_now_add=True)),
                ('tempo1', models.CharField(max_length=10)),
                ('reps1', models.CharField(max_length=10)),
                ('sets1', models.CharField(max_length=10)),
                ('rest1', models.CharField(max_length=10)),
                ('exercise2', models.CharField(max_length=100)),
                ('tempo2', models.CharField(max_length=10)),
                ('reps2', models.CharField(max_length=10)),
                ('sets2', models.CharField(max_length=10)),
                ('rest2', models.CharField(max_length=10)),
                ('exercise1', models.CharField(max_length=100)),
                ('tempo3', models.CharField(max_length=10)),
                ('reps3', models.CharField(max_length=10)),
                ('sets3', models.CharField(max_length=10)),
                ('rest3', models.CharField(max_length=10)),
                ('exercise4', models.CharField(max_length=100)),
                ('tempo4', models.CharField(max_length=10)),
                ('reps4', models.CharField(max_length=10)),
                ('sets4', models.CharField(max_length=10)),
                ('rest4', models.CharField(max_length=10)),
                ('exercise5', models.CharField(max_length=100)),
                ('tempo5', models.CharField(max_length=10)),
                ('reps5', models.CharField(max_length=10)),
                ('sets5', models.CharField(max_length=10)),
                ('rest5', models.CharField(max_length=10)),
                ('exercise6', models.CharField(max_length=100)),
                ('tempo6', models.CharField(max_length=10)),
                ('reps6', models.CharField(max_length=10)),
                ('sets6', models.CharField(max_length=10)),
                ('rest6', models.CharField(max_length=10)),
                ('exercise7', models.CharField(max_length=100)),
                ('tempo7', models.CharField(max_length=10)),
                ('reps7', models.CharField(max_length=10)),
                ('sets7', models.CharField(max_length=10)),
                ('rest7', models.CharField(max_length=10)),
                ('exercise8', models.CharField(max_length=100)),
                ('tempo8', models.CharField(max_length=10)),
                ('reps8', models.CharField(max_length=10)),
                ('sets8', models.CharField(max_length=10)),
                ('rest8', models.CharField(max_length=10)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Posted')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts_posts', to=settings.AUTH_USER_MODEL)),
                ('workouts_dislikes', models.ManyToManyField(blank=True, related_name='Workout_dislikes', to=settings.AUTH_USER_MODEL)),
                ('workouts_likes', models.ManyToManyField(blank=True, related_name='Workout_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-workouts_created_on'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_on', models.TimeField(auto_now_add=True)),
                ('Workout_comment_approval', models.BooleanField(default=False)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workoutscomments', to='routine.workouts')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
