# Generated by Django 3.2 on 2021-12-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouts',
            name='exercise3',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
