# Generated by Django 3.2 on 2021-12-23 11:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routine', '0003_auto_20211223_1018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Workouts',
            new_name='Workout',
        ),
    ]
