# Generated by Django 3.2 on 2021-12-26 00:18

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('journal_featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('journal_excerpt', models.TextField(blank=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('journal_content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_posts', to=settings.AUTH_USER_MODEL)),
                ('journal_dislikes', models.ManyToManyField(blank=True, related_name='journal_dislike', to=settings.AUTH_USER_MODEL)),
                ('journal_likes', models.ManyToManyField(blank=True, related_name='journal_like', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='JournalComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('message_body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('message_approved', models.BooleanField(default=False)),
                ('journalpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journalcomments', to='fitnessjournal.journalpost')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
