# Generated by Django 3.2 on 2021-12-25 08:53

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('post_description', models.TextField(blank=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('post_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('post_created_on', models.DateTimeField(auto_now_add=True)),
                ('post_content', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Posted')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs_posts', to=settings.AUTH_USER_MODEL)),
                ('post_dislikes', models.ManyToManyField(blank=True, related_name='post_dislikes', to=settings.AUTH_USER_MODEL)),
                ('post_likes', models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-post_created_on'],
            },
        ),
        migrations.CreateModel(
            name='PostsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_on', models.TimeField(auto_now_add=True)),
                ('post_comment_approval', models.BooleanField(default=False)),
                ('Posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postscomment', to='blogs.posts')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
