# Generated by Django 3.2 on 2021-12-25 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postscomment',
            name='Posts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postscomments', to='blogs.posts'),
        ),
    ]
