# Generated by Django 3.2 on 2021-12-16 03:33

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('article_updated_on', models.TimeField(auto_now=True)),
                ('article_summery', models.TextField()),
                ('article_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('article_video', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='video')),
                ('article_created_on', models.TimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Posted')], default=0)),
                ('article_dislikes', models.ManyToManyField(blank=True, related_name='article_dislikes', to=settings.AUTH_USER_MODEL)),
                ('article_likes', models.ManyToManyField(blank=True, related_name='article_likes', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-article_created_on'],
            },
        ),
        migrations.CreateModel(
            name='Article_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('message_created_on', models.TimeField(auto_now_add=True)),
                ('article_comment_approval', models.BooleanField(default=False)),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to='article.article')),
            ],
            options={
                'ordering': ['-message_created_on'],
            },
        ),
    ]
