# Generated by Django 3.2 on 2021-12-25 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='article_exert',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='article_summery',
        ),
        migrations.AddField(
            model_name='blog',
            name='article_description',
            field=models.TextField(blank=True),
        ),
    ]
