# Generated by Django 3.2 on 2021-12-16 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20211216_0407'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog_comment',
            new_name='BlogComment',
        ),
    ]
