# Generated by Django 3.2 on 2021-12-16 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_rename_blog_comment_blogcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='Blog',
            new_name='blog',
        ),
    ]
