# Generated by Django 3.2 on 2021-12-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_rename_blog_blogcomment_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
