# Generated by Django 3.2 on 2021-12-22 01:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_blog_excerpt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='excerpt',
        ),
        migrations.AddField(
            model_name='blog',
            name='article_content',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='article_summery',
            field=models.TextField(blank=True),
        ),
    ]
