# Generated by Django 3.2 on 2021-12-23 03:22

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('article_td', models.TextField()),
                ('routines_td', models.TextField()),
                ('recipies_td', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='HeroImage',
        ),
    ]
