# Generated by Django 3.2 on 2021-12-25 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211223_0322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainPageContent',
        ),
    ]
